version: '3.8'

services:
  mongo:
    image: mongo
    container_name: DynamischRijbaanSysteem
    ports:
      - "27017:27017"
    volumes:
      - DynamischRijbaanSysteem_data:/data/db
    restart: no

volumes:
  DynamischRijbaanSysteem_data:
